### ISSUE TITLE
Inconsistent CSS props behaviour for Button

### ISSUE THREAD

**Issue by FOMSON** [segmentio/evergreen#751] opened 2020-03-02 00:23 UTC
Apologies in advance if this is not the type of issue that should be posted here... I am very new to GitHub.

If I go on [the evergreen webisite](https://evergreen.segment.com/components/button) and add **color prop** to a Button component, like this:

`<Button appearance="minimal" color="#BF0E08" intent="none">SOME TEXT</Button>`

everything (on the website) works as expected - the text in a button become, in this example, red (i.e. the colour I put into the color prop).

However, in my own React app, this does not happen. It seems that somehow my "custom" color prop get overwritten by a default one.

A workaround for that I would is to use the style prop like this:

`style={{ color: '#084B8A'}}`

And overall my Button component looks like this now:

`<Button style={{ color: '#084B8A'}} iconBefore="manual" appearance="minimal">SOME TEXT HERE</Button>`

This allowed my to change the colour of the text as well as the colour of the icon.

I appreciate that in some cases custom CSS props will not work well (e.g. for a coloured button with custom background), but in other cases (like mine above), one would expect to be able to just replace color prop to have different colour text.

**Comment by cstrat** [comment] 2020-03-02 01:19
You are right, here is an example reproduction of the bug.
I've not run into this myself before - I do use CSS styling props a lot.

https://codesandbox.io/s/testing-css-props-on-button-9gz7m

**Comment by Chrischuck** [comment] 2020-03-02 04:20
<img width="960" alt="Screen Shot 2020-03-01 at 20 17 11" src="https://user-images.githubusercontent.com/13311268/75645214-dc589a80-5bf9-11ea-9824-0ee65872ee84.png">

Something funky is going on here, looks like `ui-box` is for some reason transforming this into a className. For now, i'd stick with the `style` attribute and only use props specified in the docs.

I'll try to see whats going on here and give you an update.

**Comment by Chrischuck** [comment] 2020-03-02 04:26
https://github.com/segmentio/evergreen/blob/master/src/typography/src/Text.js#L65

My best guess is that glamor isn't doing its job correctly...

For now I'd stick with using the `style` prop until we can figure out what's going wrong here

**Comment by Chrischuck** [comment] 2020-03-02 04:29
Update:

Looks like glamor is working fine, it's just the styles are getting overriden..

<img width="960" alt="Screen Shot 2020-03-01 at 20 28 22" src="https://user-images.githubusercontent.com/13311268/75645583-589fad80-5bfb-11ea-8491-1f231eb1f13b.png">

**Comment by colinlohner** [comment] 2020-03-02 23:41
Hey guys! Thanks for reporting this issue. I'm going take a look at it and keep you updated with the progress

**Comment by colinlohner** [comment] 2020-03-03 00:36
Seems to be a ordering issue between ui-box and glamor

**Comment by colinlohner** [comment] 2020-03-03 18:21
Hey guys, as an update, after doing some digging looks like this is going to be bigger than a quick fix. For now, I would suggest to continue using the suggested `style` prop workaround. Closing this issue for now.

**Closed by colinlohner** 2020-03-03 18:21 UTC
Labels: Status: In Progress, Type: Bug
