### ISSUE TITLE
Button color on hover

### ISSUE THREAD

**Issue by kvinodhkumar87** [segmentio/evergreen#470] opened 2019-01-06 03:30 UTC
When I'm using Button component, I'm changing the background color. But on hover it is giving the default color. How do we solve this?

**Comment by mshwery** [comment] 2019-03-11 10:49
@kvinodhkumar87 that is due to the way theming works internally – you are only applying properties to the default static state of a button, not it's pseudo states (hover, focus, active).

I would suggest using a solution that allows you to specify the full style representation – className + css, or some css-in-js solution that can be passes as `style`, a `className` or as a wrapped component.

**Comment by xAvarice** [comment] 2020-02-06 11:19
Changing the colour of an icon onHover is much worse, especially with the complexities of :hover nested selectors with css-in-js and the webpack headache.

**Comment by mshwery** [comment] 2021-07-14 23:07
This is resolved by more extensive theming support in later versions of EG. Closing as the issue is quite old.

**Closed by mshwery** 2021-07-14 23:07 UTC
