### ISSUE TITLE
Type issues for SideSheetProps.position in tsx files.

### ISSUE THREAD

**Issue by kasipavankumar** [segmentio/evergreen#1069] opened 2020-09-27 19:25 UTC
**Describe the bug**

Greetings.

When using the `SideSheet` component in a NextJS project, the TS (`.tsx`) compiler throws an error stating `Type 'string' is not assignable to type 'Pick<PositionTypes, "bottom" | "left" | "right" | "top">'`. Although the SideSheet is being rendered as expected during on the development server, the error causes the build process to fail. 

Just wanted to clarify if this a bug or am I getting something wrong?

**To Reproduce**

```ts
<SideSheet
  position={Position.LEFT} // ← Error is thrown at this line
  isShown={isMenuOpen}
  onCloseComplete={() => toggleMenuOpenState(false)}
  preventBodyScrolling
>
...
</SideSheet>

```

CodeSandBox Example: https://codesandbox.io/s/4nurm?file=/src/SideSheet.tsx

**Expected behavior**

The SideSheet is being rendered as expected but this error causes the build process to fail.

**Evergreen Version**

v5.1.1

**Screenshots**

![image](https://user-images.githubusercontent.com/44864604/94373315-54505a00-0122-11eb-8c14-e8865578d3bc.png)

**Environment:**

- OS: Windows 10 / 1909 / 64-Bit
- Browser: Mozilla Firefox
- Version: 81.0

**Comment by akleiner2** [comment] 2020-09-27 19:50
Dupe of https://github.com/segmentio/evergreen/pull/1048 -- going to merge that into master and cut a release. Thanks for reporting!

**Closed** 2020-09-27 19:53 UTC
