### ISSUE TITLE
Start evergreen app locally

### ISSUE THREAD

**Issue by jtanya34** [segmentio/evergreen#541] opened 2019-04-25 06:06 UTC
Hello!! I am a newbie with react and I am having issue running evergreen locally. 
running npm run dev for gatsby develop show this err:docs@1.0.0 dev: `gatsby develop`. Is it  something because of gatsby version?
I could run storybook locally, but how should I run evergreen?
Thanks!!
<img width="626" alt="Screen Shot 2019-04-26 at 10 50 03 AM" src="https://user-images.githubusercontent.com/30055901/56785073-2a9a5180-6811-11e9-9162-ad185eca7cb4.png">

**Comment by mshwery** [comment] 2019-05-03 20:15
When developing locally you should be able to run `yarn dev`

**Comment by mshwery** [comment] 2019-05-03 20:16
You'll also notice there is no `package-lock.json` because we use `yarn` on this project for development, so it's possible there are some pinned dependencies in the `yarn.lock` that wont be respected when you `npm install`

**Comment by jtanya34** [comment] 2019-05-05 08:09
I tried with yarn as well. webpack version gives some error.

**Comment by jtanya34** [comment] 2019-05-07 06:54
I did with yarn dev now, but files in docs/public folder are creating error.

**Comment by mshwery** [comment] 2019-05-07 13:34
Can you provide full steps to reproduce the error and information about your OS/system?

Did you `rm -rf node_modules && yarn install` before running any other yarn commands?

**Comment by jtanya34** [comment] 2019-05-07 17:01
I am using macOS Sierra, I am in master branch and docs folder  :
 1.) rm -rf node_modules 
2. yarn dev which gives this error.

**Comment by mshwery** [comment] 2019-05-07 21:16
![Screen Shot 2019-05-07 at 4 07 18 PM](https://user-images.githubusercontent.com/710752/57333774-666fc980-70e3-11e9-9e66-b00e8afdb8d9.png)

**Comment by jtanya34** [comment] 2019-05-08 05:46
During yarn install it gives some dependencies warning ,can that be a issue.
Now again cloned the repo and performed following steps:
1. cd docs
2. yarn install
which give these warnings:
<img width="1048" alt="Screen Shot 2019-05-08 at 10 55 03 AM" src="https://user-images.githubusercontent.com/30055901/57352048-b8672c80-7181-11e9-844e-c6ac7af62c4d.png">

3. yarn dev 
which gives these error:
<img width="597" alt="Screen Shot 2019-05-08 at 11 06 38 AM" src="https://user-images.githubusercontent.com/30055901/57352071-cf0d8380-7181-11e9-987b-b2adf6707d28.png">
<img width="1048" alt="Screen Shot 2019-05-08 at 10 55 03 AM" src="https://user-images.githubusercontent.com/30055901/57352073-d0d74700-7181-11e9-9ace-9926b46553d8.png">


 webpack version:webpack@4.16.5 
 yarn version : 1.15.2
Node :v11.14.0

**Comment by jtanya34** [comment] 2019-05-08 18:10
ohh , that worked! Thanks.
Now I hope I find some good first issue to contribute.

**Comment by mshwery** [comment] 2019-05-08 18:12
Yay! Alright, closing this out. Your first contribution could always be updating the readme about running the docs _after running the build_ :)

**Closed by mshwery** 2019-05-08 18:12 UTC
