### ISSUE TITLE
v6 - alignment of items changed

### ISSUE THREAD

**Issue by psiho** [segmentio/evergreen#1207] opened 2021-05-20 16:11 UTC
Sorry again for a really superficial report, but really swamped with work now so I don't have time to debug. Will as soon as I find the time.

Anyway, one of the things after upgrading to v6 is that many of my UI items changed alignment. It seems they're centered while they were aligned left in v5. Best seen in the screenshot below. I have MenuItems and Buttons, both behaving differently now. MenuItems also changed background color (in my example, previosely the "Dashboard" menu item had exactly the same color as the title "quick actions".

![screenshot-evergreen-v6](https://user-images.githubusercontent.com/1129253/119012068-fd8bdf00-b995-11eb-9f36-41fd9e9de480.png)

**Comment by akleiner2** [comment] 2021-05-21 21:24
The center-alignment is intentional for Buttons and MenuItems in the new v6 default theme. You can add some add'l CSS, to get the behavior that you're looking for, but this was a pretty intentional change from our end to get closer to the expected behavior out of the box. As for the color of the menu item, you can unset the color, but the default theme sets it to white by default. 

Going to close this out, as this looks like expected behavior!

**Closed by akleiner2** 2021-05-21 21:24 UTC
