### ISSUE TITLE
Autocomplete Popover Positioning broken inside of Sidesheet

### ISSUE THREAD

**Issue by seanemmer** [segmentio/evergreen#927] opened 2020-08-07 18:42 UTC
Hi Team,

Version: 5.0.2.

Expected Behavior:
Autocomplete Popover positioned below input field

Actual Behavior:
Autocomplete Popover positioned absolutely at top left corner

Notes:
I switched to the new ref prop: `ref={getRef}` as described in the docs

![popover error](https://user-images.githubusercontent.com/8183188/89677760-de0e4480-d8a2-11ea-935b-45c024b1532f.png)

**Comment by mshwery** [comment] 2020-08-07 18:46
Can you link us to a minimal working example of the issue @seanemmer ?

**Comment by seanemmer** [comment] 2020-08-07 19:04
> Can you link us to a minimal working example of the issue @seanemmer ?

Yes, let me cook something up.

**Comment by seanemmer** [comment] 2020-08-07 20:31
SOLVED

Apologies for the false alarm.  I did not realize that I had to use forwardRef() to pass refs down to custom components.

**Comment by recurser** [comment] 2020-08-08 05:00
@seanemmer I'm having a similar issue with `<SelectMenu />` after upgrading to v5 - are you able to provide any more detail as to how to solve it? I'm not using `ref` anywhere.

<img width="763" alt="Screen Shot 2020-08-08 at 13 59 46" src="https://user-images.githubusercontent.com/96322/89702753-724dd980-d97f-11ea-8644-89a9a10423e2.png">

**Comment by mshwery** [comment] 2020-08-08 05:10
@recurser what are you using for your menu trigger? I believe all trigger elements need to accept refs directly or must be ref-forwarding. Can you prove the select menu code snippet?

**Comment by recurser** [comment] 2020-08-08 05:47
@mshwery I can reproduce it using a simplified example from the [docs](https://evergreen.segment.com/components/select-menu):

```
<SelectMenu
  title="Select name"
  options={
    ['Apple', 'Apricot', 'Banana', 'Cherry', 'Cucumber']
      .map(label => ({ label, value: label }))
  }
>
  <Button>{'Select name...'}</Button>
</SelectMenu>

```

If I make a fresh skeleton app with `create-react-app` though it works as expected, so must be something to do with my layout. It worked fine prior to the v5 upgrade though.

<img width="1904" alt="Screen Shot 2020-08-08 at 14 46 37" src="https://user-images.githubusercontent.com/96322/89703475-1175cf80-d986-11ea-8104-35d2efa06963.png">

**Comment by recurser** [comment] 2020-08-09 00:19
@mshwery sorry my bad - it turns out I was using my own `<Button />` implementation which wraps the Evergreen component. Using the default Evergreen `<Button />` works, so I obviously need to re-write my wrapper with `forwardRef`. Feel free to close this!

**Comment by mshwery** [comment] 2020-08-09 00:25
No worries! Glad you figured it out. It might call for us providing more flexible ways to have the trigger/target ref (e.g. optional ref prop)

**Closed** 2020-08-09 00:25 UTC

**Comment by seanemmer** [comment] 2020-08-10 16:21
@mshwery what do you think of updating the popover intro docs to include the text from the release notes:

Its target, as a single child element or a function. _The target must be a DOM node or component that can forward refs to a DOM node._

Also, it may be worthwhile to add a note to the "children" prop under Autocomplete to the effective of:

Function that will render the 'filter' component.  _Must be a valid [Popover Target](https://evergreen.segment.com/components/popover)_
