### ISSUE TITLE
Depedency error: The required JS dependency "dom-helpers/util/inDOM" is not available, it was required by "node_modules/evergreen-ui/commonjs/portal/src/Portal.js".

### ISSUE THREAD

**Issue by beders** [segmentio/evergreen#858] opened 2020-06-13 21:25 UTC
**Describe the bug**
Can't compile evergreen-ui.

I'm getting the following error:
The required JS dependency "dom-helpers/util/inDOM" is not available, it was required by "node_modules/evergreen-ui/commonjs/portal/src/Portal.js".

**To Reproduce**
`$ npm install --save evergreen-ui `

**Expected behavior**
All dependencies work

**Evergreen Version**
4.27.4

DOM-helpers version: 5.1.4
(so vastly newer than the one evergreen needs)
(and indeed:
`$ ls: node_modules/dom-helpers/util: No such file or directory`
)
also: in Portal.js:
```
var _inDOM = _interopRequireDefault(require("dom-helpers/util/inDOM"));
```

**Environment (please complete the following information):**
 - OS: MacOS catalina
 - Browser Firefox
 - Version latest

**Additional context**
Error created by the Shadow-cljs compiler (this is a ClojureScript project).

**Comment by mshwery** [comment] 2020-07-28 18:28
This is probably happening because you have a conflict in your resolved version of `dom-helpers`. You can see that Evergreen relies on `dom-helpers@^3.2.1` per the package.json and yarn.lock files.

**Comment by mshwery** [comment] 2020-09-06 21:56
This seems specific to the way the project is being compiled/bundled and we have not been able to reproduce it ourselves. Closing for now!

**Closed by mshwery** 2020-09-06 21:56 UTC
Labels: Type: Bug

**Comment by tggreene** [comment] 2020-09-25 08:33
Hi @mshwery, I believe this is a result of the fact that evergreen-ui's [dependency on react-transition-group "4.4.1"](https://github.com/segmentio/evergreen/blob/15d8b463ae4da6eef700e6d97729c4c614055209/package.json#L70) [has a dependency on dom-helpers "5.0.1"](https://github.com/reactjs/react-transition-group/blob/399f26998a5cf2449798a02c755e5808e9b39ddd/package.json#L61) whilst evergreen-ui also [has a dependency on dom-helpers "3.2.1"](https://github.com/segmentio/evergreen/blob/15d8b463ae4da6eef700e6d97729c4c614055209/package.json#L61).

The tool @beders is using, shadow-cljs, is a clojurescript build tool that disallows nested dependencies to eliminate issues with conflicting library versions, I've come across the same issue just now. Whilst the bundler this project uses may be able to take the parts of both versions of the library, it does make it trickier to use in other environments, and this looks like a really nice library to use in conjunction with reagent!

It looks quite easy to refactor the evergreen-ui usage to be compatible with the new api `dom-helpers/util/inDOM/canUseDom` => `dom-helpers/canUseDom` I may have a go at a PR for this if that sounds reasonable?
